### ISSUE TITLE
Workflow Sample Creation Tracking issue

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/dotnet-sdk#1064]
**Description:**
This Epic will be used to track the samples we'll need to create around Dapr Workflows. Samples will use the existing [workflowConsoleApp](https://github.com/dapr/dotnet-sdk/tree/master/examples/Workflow/WorkflowConsoleApp) and highlight key patterns for Dapr Workflows

**How it'll work:** We'll create a new directory in the [dotnet-sdk/examples/workflow](https://github.com/dapr/dotnet-sdk/tree/master/examples/Workflow) directory called "Samples". The Samples directory will contain each sample's program files and each sample will highlight a specific pattern (i.e., taskChaining.cs, K8sWorkflowscs, fanOutFanIn.cs etc.). When users want to try a sample, they'll swap the original [Program.cs](https://github.com/dapr/dotnet-sdk/blob/master/examples/Workflow/WorkflowConsoleApp/Program.cs) file with one from the sample program files and then they run the console app with the new program to try the pattern. 

**Patterns to create:**
- [ ] https://github.com/dapr/dotnet-sdk/issues/1061
- [ ] https://github.com/dapr/dotnet-sdk/issues/1062
- [ ] https://github.com/dapr/dotnet-sdk/issues/1063

**Comment by paulyuk** [comment]
I like this list a lot.  Few more suggestions:
- Workflow Sample: Trigger workflow from an HTTP webhook (very similar if not easier than input binding)
- Workflow Sample: Trigger workflow from an Cron/timer binding webhook (special case of input binding, but probably merits its own)
- Some scenario based workflows: like file/document processing, polling, aggregate math/data calculation
